# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ti3yndLKVBRcoFHTCdPkB34e6YNIIdF5
"""

from abc import ABC, abstractmethod

class Course(ABC):

    def __init__(self, course_id: str, name: str, credit_hours: int, cost_per_credit: float):
        self._course_id = course_id
        self._name = name
        self.__credit_hours = credit_hours
        self.__cost_per_credit = cost_per_credit

    @property
    def course_id(self):
        return self._course_id

    @property
    def name(self):
        return self._name

    @property
    def credit_hours(self):
        return self.__credit_hours

    @credit_hours.setter
    def credit_hours(self, value: int):
        if not isinstance(value, int) or value < 1 or value > 6:
            raise ValueError("Credit hours must be an integer between 1 and 6.")
        self.__credit_hours = value

    @property
    def cost_per_credit(self):
        return self.__cost_per_credit

    @cost_per_credit.setter
    def cost_per_credit(self, value: float):
        if value <= 0:
            raise ValueError("Cost per credit must be a positive number.")
        self.__cost_per_credit = value

    def base_tuition(self) -> float:
        return self.__credit_hours * self.__cost_per_credit

    @abstractmethod
    def calculate_tuition(self) -> float:
        pass

    @abstractmethod
    def display_course_info(self):
        pass


class PracticalLab(Course):

    EQUIPMENT_FEE = 150.00

    def __init__(self, course_id: str, name: str, credit_hours: int,
                 cost_per_credit: float, safety_gear_required: bool = False):
        super().__init__(course_id, name, credit_hours, cost_per_credit)
        self.safety_gear_required = safety_gear_required

    def calculate_tuition(self) -> float:
        return self.base_tuition() + self.EQUIPMENT_FEE

    def display_course_info(self):
        gear = "Yes" if self.safety_gear_required else "No"
        print(f"  [{self.course_id}] {self.name}")
        print(f"        Type        : Practical Lab")
        print(f"        Credits     : {self.credit_hours} hrs  |  Base: ${self.base_tuition():.2f}")
        print(f"        Equipment   : +${self.EQUIPMENT_FEE:.2f} flat fee")
        print(f"        Safety Gear : {gear}")
        print(f"        Total Cost  : ${self.calculate_tuition():.2f}")


class TheoreticalLecture(Course):

    TECH_FEE_RATE = 0.05

    def __init__(self, course_id: str, name: str, credit_hours: int,
                 cost_per_credit: float, hall_capacity: int = 200,
                 online_link: str = ""):
        super().__init__(course_id, name, credit_hours, cost_per_credit)
        self._hall_capacity = hall_capacity
        self.online_link = online_link

    @property
    def hall_capacity(self):
        return self._hall_capacity

    @hall_capacity.setter
    def hall_capacity(self, value: int):
        if not isinstance(value, int) or value < 1:
            raise ValueError("Hall capacity must be a positive integer.")
        self._hall_capacity = value

    def calculate_tuition(self) -> float:
        tech_fee = self.base_tuition() * self.TECH_FEE_RATE
        return self.base_tuition() + tech_fee

    def display_course_info(self):
        tech_fee = self.base_tuition() * self.TECH_FEE_RATE
        link_display = self.online_link if self.online_link else "N/A"
        print(f"  [{self.course_id}] {self.name}")
        print(f"        Type        : Theoretical Lecture")
        print(f"        Credits     : {self.credit_hours} hrs  |  Base: ${self.base_tuition():.2f}")
        print(f"        Tech Fee    : +${tech_fee:.2f} (5% of base)")
        print(f"        Hall Cap.   : {self.hall_capacity} students")
        print(f"        Online Link : {link_display}")
        print(f"        Total Cost  : ${self.calculate_tuition():.2f}")


class StudentSchedule:

    def __init__(self, student_name: str):
        self.student_name = student_name
        self._courses: list[Course] = []

    def add_course(self, course: Course) -> bool:
        if any(c.course_id == course.course_id for c in self._courses):
            return False
        self._courses.append(course)
        return True

    def remove_course(self, course_id: str) -> bool:
        for c in self._courses:
            if c.course_id == course_id:
                self._courses.remove(c)
                return True
        return False

    def is_registered(self, course_id: str) -> bool:
        return any(c.course_id == course_id for c in self._courses)

    def view_schedule(self):
        if not self._courses:
            print("\n  Your schedule is empty.")
            return
        print(f"\n  {'─'*52}")
        print(f"  Registered Courses for: {self.student_name}")
        print(f"  {'─'*52}")
        for course in self._courses:
            print(f"  • [{course.course_id}] {course.name}  ({course.credit_hours} credits)")
        print(f"  {'─'*52}")

    def print_tuition_bill(self):
        if not self._courses:
            print("\n  No courses registered. Nothing to bill.")
            return

        divider = "═" * 58
        thin = "─" * 58

        print(f"\n  {divider}")
        print(f"  {'CAIRO TECH UNIVERSITY':^56}")
        print(f"  {'SEMESTER TUITION BILL':^56}")
        print(f"  {divider}")
        print(f"  Student : {self.student_name}")
        print(f"  {thin}")
        print(f"  {'COURSE':<30} {'CREDITS':>7} {'TOTAL':>14}")
        print(f"  {thin}")

        grand_total = 0.0
        for course in self._courses:
            cost = course.calculate_tuition()
            grand_total += cost
            label = course.name[:28]
            print(f"  {label:<30} {course.credit_hours:>5} cr   ${cost:>10.2f}")

        print(f"  {thin}")
        print(f"  {'GRAND TOTAL':<38} ${grand_total:>14.2f}")
        print(f"  {divider}")
        print(f"  * Lab courses include a $150.00 equipment fee.")
        print(f"  * Lecture courses include a 5% technology fee.")
        print(f"  {divider}\n")


def build_catalog() -> dict[str, Course]:
    return {
        "CS101": TheoreticalLecture("CS101", "Introduction to Computer Science", 3, 120.0,
                                    hall_capacity=250, online_link="meet.cairouniv.edu/cs101"),
        "CS102": PracticalLab("CS102", "Programming Lab I", 2, 130.0, safety_gear_required=False),
        "CS201": TheoreticalLecture("CS201", "Data Structures & Algorithms", 3, 135.0,
                                    hall_capacity=180),
        "CS202": PracticalLab("CS202", "Data Structures Lab", 2, 130.0, safety_gear_required=False),
        "EE101": TheoreticalLecture("EE101", "Signals and Systems", 3, 125.0,
                                    hall_capacity=200, online_link="meet.cairouniv.edu/ee101"),
        "EE102": PracticalLab("EE102", "Electronics Lab", 2, 130.0, safety_gear_required=True),
        "MA101": TheoreticalLecture("MA101", "Calculus I", 4, 110.0, hall_capacity=300),
        "AI301": TheoreticalLecture("AI301", "Artificial Intelligence", 3, 145.0,
                                    hall_capacity=120, online_link="meet.cairouniv.edu/ai301"),
        "AI302": PracticalLab("AI302", "AI & Machine Learning Lab", 2, 140.0,
                               safety_gear_required=False),
        "CA201": TheoreticalLecture("CA201", "Computer Architecture", 3, 130.0, hall_capacity=160),
    }


def print_banner():
    print("\n" + "═" * 58)
    print("       CAIRO TECH UNIVERSITY")
    print("       Interactive Registration Portal")
    print("═" * 58)

def print_menu():
    print("\n  ┌─────────────────────────────────┐")
    print("  │         MAIN MENU               │")
    print("  ├─────────────────────────────────┤")
    print("  │  [1]  View Available Courses     │")
    print("  │  [2]  Register for a Course      │")
    print("  │  [3]  View My Schedule           │")
    print("  │  [4]  Drop a Course              │")
    print("  │  [5]  Print Tuition Bill         │")
    print("  │  [6]  Exit                       │")
    print("  └─────────────────────────────────┘")

def view_catalog(catalog: dict[str, Course]):
    print(f"\n  {'─'*58}")
    print(f"  {'AVAILABLE COURSES THIS SEMESTER':^56}")
    print(f"  {'─'*58}")
    for course in catalog.values():
        course.display_course_info()
        print()

def register_course(catalog: dict[str, Course], schedule: StudentSchedule):
    print("\n  Enter the Course ID to register (e.g. CS101): ", end="")
    code = input().strip().upper()
    if code not in catalog:
        print(f"\n  ✗ Course '{code}' not found in the catalog.")
        return
    if schedule.is_registered(code):
        print(f"\n  ✗ You are already registered for {catalog[code].name}.")
        return
    schedule.add_course(catalog[code])
    print(f"\n  ✓ Successfully registered for: {catalog[code].name}")

def drop_course(catalog: dict[str, Course], schedule: StudentSchedule):
    print("\n  Enter the Course ID to drop: ", end="")
    code = input().strip().upper()
    if schedule.remove_course(code):
        print(f"\n  ✓ '{code}' has been removed from your schedule.")
    else:
        print(f"\n  ✗ You are not registered for '{code}'.")

def get_student_name() -> str:
    while True:
        print("\n  Please enter your full name to begin: ", end="")
        name = input().strip()
        if name:
            return name
        print("  Name cannot be empty. Please try again.")

def main():
    print_banner()
    student_name = get_student_name()
    catalog = build_catalog()
    schedule = StudentSchedule(student_name)

    print(f"\n  Welcome, {student_name}! Use the menu below to manage your registration.")

    while True:
        print_menu()
        print("  Select an option: ", end="")

        try:
            choice = input().strip()

            if choice == "1":
                view_catalog(catalog)
            elif choice == "2":
                register_course(catalog, schedule)
            elif choice == "3":
                schedule.view_schedule()
            elif choice == "4":
                drop_course(catalog, schedule)
            elif choice == "5":
                schedule.print_tuition_bill()
            elif choice == "6":
                print(f"\n  Goodbye, {student_name}! Have a great semester.\n")
                break
            else:
                print("\n  ✗ Invalid option. Please enter a number between 1 and 6.")

        except KeyboardInterrupt:
            print(f"\n\n  Session interrupted. Goodbye, {student_name}!\n")
            break
        except Exception as e:
            print(f"\n  ✗ An unexpected error occurred: {e}")


if __name__ == "__main__":
    main()